In [6]:
import win32com.client
import datetime as dt
import pandas as pd
import xlrd
import glob
import os
import win32com.client
import datetime as dt


myFiles = glob.glob('*.xlsx')
print(myFiles)
for file in myFiles:
    print(file)
    df=pd.read_excel(file,header=0,dtype=object)

['ML_TRAINING_DATA_ALL.xlsx']
ML_TRAINING_DATA_ALL.xlsx

In [3]:
outlook = win32com.client.Dispatch('Outlook.Application').GetNamespace('MAPI')
namespace = outlook.Session
recipient = namespace.CreateRecipient("deesaw@deloitte.com")
inbox = outlook.GetDefaultFolder(6)#(recipient, 6)
messages = inbox.Items
email_subject = []
i=0
for x in messages:
    i=i+1
    sub = x.Subject
    email_subject.append(sub)
    if i >21000:
        break

In [4]:
df1=pd.DataFrame()
for d in df['UID']:
    df1['UID']=d
    for e in email_subject:
        if str(d) in e:
            df1['Subject']=e

KeyError: 'UID'

In [8]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Values,NaN,NaN,NaN
2,Payer,D/C Ind.,Min of Percent of Pay Amt / Inv. Amt.,Max of Percent of Pay Amt / Inv. Amt.,Average of Percent of Pay Amt / Inv. Amt.,StdDevp of Percent of Pay Amt / Inv. Amt.
3,*,S,5.09762,54987.3,506.489,4724.1
4,10000100,S,96.0417,98,97.0208,0.979167
...,...,...,...,...,...,...
576,301136,S,2692.05,506700,98644.8,80526.9
577,70000000,S,50,109.928,99.7928,4.046
578,70000010,S,2.29885,100.075,94.7743,21.4508
579,(blank),(blank),NaN,NaN,NaN,NaN
580,Grand Total,NaN,0,8.92145e+07,29163.8,541784